Algoritmo "4OPERACOES"

Var
soma, sub, mult, divi : real
x, y : real

Inicio
escreva ("Digite o valor de x", x)
leia (x)
escreva ("Digite o valor de y", y)
leia (y)
limpatela
soma <- (x + y)
escreval ("A soma dos dois valores é ", soma)
sub <- (x - y)
escreval ("A subtração dos dois valores é ", sub)
mult <- (x * y)
escreval ("A multiplicação dos dois valores é ", mult)
divi <- (x / y)
escreval ("A divisão dos dois valores é ", divi)

Fimalgoritmo